export default {
  GET_ITEM_START: 'ToDo/GET_ITEM_START',
  GET_ITEM_SUCCESS: 'ToDo/GET_ITEM_SUCCESS',
  GET_ITEM_FAILURE: 'ToDo/GET_ITEM_FAILURE',

  ADD_ITEM_START: 'ToDo/ADD_ITEM_START',
  ADD_ITEM_SUCCESS: 'ToDo/ADD_ITEM_SUCCESS',
  ADD_ITEM_FAILURE: 'ToDo/ADD_ITEM_FAILURE',

  DELETE_ITEM: 'ToDo/DELETE_ITEM',
  // DELETE_ITEM: 'ToDo/DELETE_ITEM',
  // DELETE_ITEM: 'ToDo/DELETE_ITEM',

  CHANGE_ITEM: 'ToDo/CHANGE_ITEM',
  // CHANGE_ITEM: 'ToDo/CHANGE_ITEM',
  // CHANGE_ITEM: 'ToDo/CHANGE_ITEM',

  ADD_ID_EDIT_ITEM: 'ToDo/ADD_ID_EDIT_ITEM',
  DELETE_ID_EDIT_ITEM: 'ToDo/DELETE_ID_EDIT_ITEM',
};
